import React, { useState, useEffect, useRef } from "react";
import { DOMAIN_COURSES, LEARNING_DOMAINS } from "../data/domainData";
import { getCourseContent, CourseContentDetail, TierAssessment } from "../data/courseContentData";
import {
  getCourseAssessmentRecord,
  recordAssessmentAttempt,
  CourseAssessmentRecord,
} from "../services/courseAssessmentService";
import { AssessmentSubmission } from "../types";
import { slate, coral, emerald, muted, border, panel, bg } from "../components/AppShell";
import CourseContentModal from "../components/CourseContentModal";
import { generateRagAssessment, scoreRagAssessment, RagAssessmentSession } from "../services/api";

export default function AssessmentsPage({
  initialCourseId,
  initialTier = "easy",
  onSubmitAssessment,
  showToast,
  onCourseCompleted,
  ragAssessmentSource,
  onRagAssessmentStarted,
}: {
  initialCourseId?: string;
  initialTier?: "easy" | "medium" | "difficult";
  onSubmitAssessment: (sub: AssessmentSubmission) => void;
  showToast: (m: string) => void;
  onCourseCompleted?: (courseId: string) => void;
  ragAssessmentSource?: { id: string; title: string } | null;
  onRagAssessmentStarted?: () => void;
}) {
  const [selectedCourseId, setSelectedCourseId] = useState<string>(
    initialCourseId || DOMAIN_COURSES[0].id
  );
  const [selectedDomainFilter, setSelectedDomainFilter] = useState<string>("All");
  const [selectedTier, setSelectedTier] = useState<"easy" | "medium" | "difficult">(
    initialTier
  );

  // Quiz state
  const [currentIdx, setCurrentIdx] = useState<number>(0);
  const [selectedOptions, setSelectedOptions] = useState<Record<number, number>>({});
  const [isSubmitted, setIsSubmitted] = useState<boolean>(false);
  const [latestScorePercent, setLatestScorePercent] = useState<number | null>(null);
  const [studyModalCourseId, setStudyModalCourseId] = useState<string | null>(null);
  const [ragSession, setRagSession] = useState<RagAssessmentSession | null>(null);
  const [isGeneratingRag, setIsGeneratingRag] = useState(false);
  // Track which source id has already triggered auto-generation to prevent re-firing
  const lastAutoGeneratedSourceId = useRef<string | null>(null);

  // Load course content & record — use the selected course data, with a safe fallback
  const selectedCourseData = DOMAIN_COURSES.find((c) => c.id === selectedCourseId);
  const courseContent = getCourseContent(selectedCourseId) || getCourseContent(selectedCourseData?.id || DOMAIN_COURSES[0].id) || getCourseContent(DOMAIN_COURSES[0].id)!;
  // Override title/domain from DOMAIN_COURSES if the content map entry doesn't match the selected course
  const resolvedCourseTitle = selectedCourseData?.title || courseContent.title;
  const resolvedDomainName = LEARNING_DOMAINS.find((d) => d.id === (selectedCourseData?.domainId || courseContent.domainId))?.name || courseContent.domainName;
  const [assessmentRecord, setAssessmentRecord] = useState<CourseAssessmentRecord>(() =>
    getCourseAssessmentRecord(selectedCourseId)
  );

  // Refresh record when course changes
  useEffect(() => {
    setAssessmentRecord(getCourseAssessmentRecord(selectedCourseId));
    setCurrentIdx(0);
    setSelectedOptions({});
    setIsSubmitted(false);
    setLatestScorePercent(null);
    setRagSession(null);
  }, [selectedCourseId]);

  // Handle tier change
  const handleSelectTier = (tier: "easy" | "medium" | "difficult") => {
    setSelectedTier(tier);
    setCurrentIdx(0);
    setSelectedOptions({});
    setIsSubmitted(false);
    setLatestScorePercent(null);
    setRagSession(null);
  };

  const currentTierAssessment: TierAssessment = courseContent.assessments[selectedTier];
  // Only show RAG placeholder when user is explicitly in 'local' mode, not for iGOT courses
  const isLocalRagMode = selectedDomainFilter === "local" && ragAssessmentSource !== null;
  const questions = ragSession?.questions || (isLocalRagMode ? [{
    id: "rag-pending",
    question: isGeneratingRag
      ? "Generating 15 document-grounded questions from the selected PDF…"
      : "The document assessment could not be generated. Confirm that the PDF was indexed by the running AI engine, then re-upload it and try again.",
    options: [],
    correctIndex: -1,
    explanation: "",
    sourceDocument: ragAssessmentSource!.title,
    sourcePage: 1,
  }] : currentTierAssessment.questions);
  const currentQ = questions[currentIdx] || questions[0];
  const totalQuestions = questions.length;

  const handleOptionSelect = (optIndex: number) => {
    if (isSubmitted) return;
    setSelectedOptions((prev) => ({ ...prev, [currentIdx]: optIndex }));
  };

  const handleGenerateRagAssessment = async (source = ragAssessmentSource) => {
    setIsGeneratingRag(true);
    const difficulty = selectedTier === "easy" ? 1 : selectedTier === "medium" ? 3 : 5;
    const session = await generateRagAssessment({ employeeId: "usr-001", competencyId: selectedCourseId, competencyName: source?.title || resolvedDomainName, difficulty, questionCount: 15, documentId: source?.id });
    setIsGeneratingRag(false);
    if (!session) {
      showToast("AI assessment could not be generated. Start the backengine and index an approved PDF first.");
      return;
    }
    setRagSession(session);
    setCurrentIdx(0);
    setSelectedOptions({});
    setIsSubmitted(false);
    setLatestScorePercent(null);
    showToast("OpenRouter generated a RAG-grounded assessment from indexed training evidence.");
  };

  useEffect(() => {
    // Only auto-generate when a NEW source is provided (not when cleared or re-rendered)
    if (ragAssessmentSource && ragAssessmentSource.id !== lastAutoGeneratedSourceId.current) {
      lastAutoGeneratedSourceId.current = ragAssessmentSource.id;
      setSelectedDomainFilter("local");
      handleGenerateRagAssessment(ragAssessmentSource);
    } else if (!ragAssessmentSource) {
      // Source was cleared (e.g. user clicked Assess on iGOT course) — reset to course mode
      lastAutoGeneratedSourceId.current = null;
      setSelectedDomainFilter("All");
      setRagSession(null);
    }
  }, [ragAssessmentSource]);

  const handleGradeAssessment = async () => {
    if (ragSession) {
      const result = await scoreRagAssessment({
        assessmentId: ragSession.assessmentId,
        employeeId: "usr-001",
        competencyId: courseContent.courseId,
        answers: questions.map((question, index) => ({ questionId: question.id, selectedOption: String.fromCharCode(65 + (selectedOptions[index] ?? -1)) })),
      });
      if (!result) {
        showToast("The authoritative assessment session could not be scored. Please retry while the backengine is online.");
        return;
      }
      const evaluatedQuestions = questions.map((question) => {
        const review = result.questions.find((item) => item.id === question.id);
        return review ? { ...question, correctIndex: review.correctIndex, explanation: review.explanation, sourceDocument: review.sourceDocument, sourcePage: review.sourcePage } : question;
      });
      const scorePct = Math.round(result.scorePercent);
      const localDocumentTitle = ragAssessmentSource?.title || (evaluatedQuestions[0] as any)?.sourceDocument || "Local uploaded document";
      setRagSession({ ...ragSession, questions: evaluatedQuestions as any });
      setLatestScorePercent(scorePct);
      setIsSubmitted(true);
      const { record: updatedRecord, newlyCompletedCourse } = recordAssessmentAttempt(selectedCourseId, selectedTier, scorePct, totalQuestions, { courseTitle: localDocumentTitle, domainName: "Local uploaded document", level: courseContent.level, correctCount: result.correctCount, userAnswers: selectedOptions, questions: evaluatedQuestions as any });
      setAssessmentRecord(updatedRecord);
      if (scorePct >= 70 && newlyCompletedCourse && onCourseCompleted) onCourseCompleted(selectedCourseId);
      showToast(scorePct >= 70 ? `Verified AI assessment passed with ${scorePct}%.` : `Verified score: ${scorePct}%. Review the grounded explanations and retry.`);
      onSubmitAssessment({ competency: "Local uploaded document", difficulty: selectedTier, score: result.correctCount, total: totalQuestions, percentage: scorePct, previousLevel: Math.max(1, parseInt(courseContent.level) - 1), newLevel: scorePct >= 70 ? parseInt(courseContent.level) : Math.max(1, parseInt(courseContent.level) - 1), masteryTier: scorePct >= 80 ? "Strong Mastery" : scorePct >= 70 ? "Proficient" : "Developing", sourceDocument: localDocumentTitle, sourcePage: (evaluatedQuestions[0] as any)?.sourcePage || 1, nextRecommendedCourse: "Next Cadre Progression Module" });
      return;
    }
    let correct = 0;
    questions.forEach((q, idx) => {
      if (selectedOptions[idx] === q.correctIndex) {
        correct++;
      }
    });

    const scorePct = Math.round((correct / totalQuestions) * 100);
    setLatestScorePercent(scorePct);
    setIsSubmitted(true);

    const { record: updatedRecord, newlyCompletedCourse } = recordAssessmentAttempt(
      selectedCourseId,
      selectedTier,
      scorePct,
      totalQuestions,
      {
        courseTitle: resolvedCourseTitle,
        domainName: resolvedDomainName,
        level: courseContent.level,
        correctCount: correct,
        userAnswers: selectedOptions,
        questions: questions,
      }
    );
    setAssessmentRecord(updatedRecord);

    if (scorePct >= 70) {
      if (newlyCompletedCourse) {
        showToast(`🎉 Outstanding! All 3 tiers passed. Course "${resolvedCourseTitle}" marked as COMPLETED!`);
        if (onCourseCompleted) onCourseCompleted(selectedCourseId);
      } else {
        showToast(`Tier ${selectedTier.toUpperCase()} Passed with ${scorePct}%!`);
      }
    } else {
      showToast(`Score: ${scorePct}% (70% required to pass). Review study materials and retry.`);
    }

    // Submit report
    const sub: AssessmentSubmission = {
      competency: resolvedDomainName,
      difficulty: selectedTier === "easy" ? "Foundational" : selectedTier === "medium" ? "Intermediate" : "Advanced",
      score: correct,
      total: totalQuestions,
      percentage: scorePct,
      previousLevel: Math.max(1, parseInt(courseContent.level) - 1),
      newLevel: scorePct >= 70 ? parseInt(courseContent.level) : Math.max(1, parseInt(courseContent.level) - 1),
      masteryTier: scorePct >= 80 ? "Strong Mastery" : scorePct >= 70 ? "Proficient" : "Developing",
      sourceDocument: `${courseContent.provider} — ${resolvedCourseTitle}`,
      sourcePage: `Module 1-4`,
      nextRecommendedCourse: "Next Cadre Progression Module",
    };
    onSubmitAssessment(sub);
  };

  const easyPassed = assessmentRecord.easy?.passed ?? false;
  const mediumPassed = assessmentRecord.medium?.passed ?? false;
  const difficultPassed = assessmentRecord.difficult?.passed ?? false;
  const allTiersPassed = assessmentRecord.allTiersPassed;

  const filteredCourses = DOMAIN_COURSES.filter((c) => {
    return selectedDomainFilter === "All" || c.domainId === selectedDomainFilter;
  });

  return (
    <div style={{ flex: 1, display: "flex", overflow: "hidden", background: bg }}>
      {/* Course Sidebar Navigator */}
      <div
        style={{
          width: 320,
          minWidth: 320,
          background: "#fff",
          borderRight: `1px solid ${border}`,
          display: "flex",
          flexDirection: "column",
          overflow: "hidden",
        }}
      >
        <div style={{ padding: "16px 18px", borderBottom: `1px solid ${border}` }}>
          <div style={{ fontSize: 13, fontWeight: 800, color: slate, marginBottom: 8 }}>
            Course Assessment Selector
          </div>
          <select
            value={selectedDomainFilter}
            onChange={(e) => setSelectedDomainFilter(e.target.value)}
            style={{
              width: "100%",
              padding: "6px 10px",
              border: `1px solid ${border}`,
              background: panel,
              fontSize: 11,
              color: slate,
              borderRadius: 4,
            }}
          >
            <option value="All">All 7 Learning Streams</option>
            <option value="local">Local Uploaded Documents</option>
            {LEARNING_DOMAINS.map((d) => (
              <option key={d.id} value={d.id}>
                {d.icon} {d.name}
              </option>
            ))}
          </select>
        </div>

        {/* Course List */}
        <div style={{ flex: 1, overflowY: "auto", padding: "10px 12px", display: "flex", flexDirection: "column", gap: 6 }}>
          {selectedDomainFilter === "local" && ragAssessmentSource ? (
            <div style={{ padding: "12px", border: `1px solid ${coral}`, background: "#FFF5F3", borderRadius: 6 }}>
              <div style={{ fontSize: 9, color: coral, fontWeight: 800, marginBottom: 5 }}>LOCAL RAG SOURCE · 15 MCQs</div>
              <div style={{ fontSize: 12, color: slate, fontWeight: 700, lineHeight: 1.4 }}>{ragAssessmentSource.title}</div>
              <div style={{ fontSize: 10, color: muted, marginTop: 6 }}>OpenRouter questions are grounded only in this indexed PDF.</div>
            </div>
          ) : selectedDomainFilter === "local" ? (
            <div style={{ padding: "14px", border: `1px dashed ${border}`, background: panel, borderRadius: 6, fontSize: 12, color: muted, lineHeight: 1.5 }}>
              No local AI assessment yet. Upload and index a PDF in Training Materials, then select <b>Generate with AI</b> on that document.
            </div>
          ) : filteredCourses.map((c) => {
            const isSelected = c.id === courseContent.courseId;
            const rec = getCourseAssessmentRecord(c.id);
            const passedTiers = [rec.easy?.passed, rec.medium?.passed, rec.difficult?.passed].filter(Boolean).length;

            return (
              <div
                key={c.id}
                onClick={() => setSelectedCourseId(c.id)}
                style={{
                  padding: "10px 12px",
                  border: `1px solid ${isSelected ? coral : border}`,
                  background: isSelected ? "#FFF5F3" : "#fff",
                  borderRadius: 6,
                  cursor: "pointer",
                }}
              >
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 4 }}>
                  <span style={{ fontSize: 9, color: muted, fontFamily: "'Space Grotesk', sans-serif" }}>
                    Level {c.level} · {c.duration_hours}h
                  </span>
                  {rec.allTiersPassed ? (
                    <span style={{ fontSize: 9, color: emerald, fontWeight: 800, fontFamily: "'Space Grotesk', sans-serif" }}>
                      ✓ COMPLETED
                    </span>
                  ) : (
                    <span style={{ fontSize: 9, color: passedTiers > 0 ? coral : muted, fontFamily: "'Space Grotesk', sans-serif" }}>
                      {passedTiers}/3 TIERS
                    </span>
                  )}
                </div>
                <div style={{ fontSize: 12, fontWeight: isSelected ? 700 : 600, color: isSelected ? coral : slate, lineHeight: 1.35 }}>
                  {c.title}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Main Assessment Canvas */}
      <div style={{ flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" }}>
        {/* Header Strip */}
        <div
          style={{
            padding: "18px 28px",
            background: "#fff",
            borderBottom: `1px solid ${border}`,
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <div>
            <div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 4 }}>
              <span
                style={{
                  padding: "2px 8px",
                  background: "#D1FAE5",
                  border: `1px solid ${emerald}`,
                  color: emerald,
                  fontSize: 10,
                  fontWeight: 700,
                  fontFamily: "'Space Grotesk', sans-serif",
                }}
              >
                iGOT 3-TIER EVALUATION
              </span>
              <span style={{ fontSize: 11, color: muted }}>{resolvedDomainName}</span>
            </div>
            <div style={{ fontSize: 18, fontWeight: 800, color: slate }}>
              {isLocalRagMode && ragAssessmentSource ? ragAssessmentSource.title : resolvedCourseTitle}
            </div>
          </div>

          <div style={{ display: "flex", gap: 10, alignItems: "center" }}>
            <button
              onClick={() => setStudyModalCourseId(courseContent.courseId)}
              style={{
                padding: "6px 14px",
                background: "#fff",
                border: `1px solid ${border}`,
                color: slate,
                fontSize: 12,
                fontWeight: 700,
                borderRadius: 4,
                cursor: "pointer",
              }}
            >
              📖 Read Course Material
            </button>
            <button
              onClick={() => handleGenerateRagAssessment()}
              disabled={isGeneratingRag || isSubmitted}
              hidden
              style={{ padding: "6px 14px", background: isGeneratingRag ? panel : slate, border: `1px solid ${slate}`, color: isGeneratingRag ? muted : "#fff", fontSize: 12, fontWeight: 700, borderRadius: 4, cursor: isGeneratingRag || isSubmitted ? "not-allowed" : "pointer" }}
            >
              {isGeneratingRag ? "Generating..." : ragSession ? "RAG Assessment Active" : "Generate with AI"}
            </button>
            {allTiersPassed ? (
              <span
                style={{
                  padding: "6px 14px",
                  background: "#D1FAE5",
                  border: `1px solid ${emerald}`,
                  color: emerald,
                  fontSize: 12,
                  fontWeight: 800,
                  borderRadius: 4,
                  fontFamily: "'Space Grotesk', sans-serif",
                }}
              >
                🏆 100% COURSE COMPLETED
              </span>
            ) : (
              <span
                style={{
                  padding: "6px 14px",
                  background: "#FFF5F3",
                  border: `1px solid ${coral}`,
                  color: coral,
                  fontSize: 11,
                  fontWeight: 700,
                  borderRadius: 4,
                  fontFamily: "'Space Grotesk', sans-serif",
                }}
              >
                {[easyPassed, mediumPassed, difficultPassed].filter(Boolean).length} of 3 Tiers Passed
              </span>
            )}
          </div>
        </div>

        {/* Tier Selector Bar */}
        <div
          style={{
            padding: "12px 28px",
            background: "#FAFCFE",
            borderBottom: `1px solid ${border}`,
            display: "flex",
            alignItems: "center",
            gap: 16,
          }}
        >
          <span style={{ fontSize: 11, fontWeight: 700, color: muted, fontFamily: "'Space Grotesk', sans-serif" }}>
            SELECT ASSESSMENT DIFFICULTY:
          </span>
          <div style={{ display: "flex", gap: 8 }}>
            {[
              { id: "easy" as const, label: "🟢 Easy (Foundations)", passed: easyPassed, score: assessmentRecord.easy?.score },
              { id: "medium" as const, label: "🟡 Medium (Methodologies)", passed: mediumPassed, score: assessmentRecord.medium?.score },
              { id: "difficult" as const, label: "🔴 Difficult (Scenarios & Audits)", passed: difficultPassed, score: assessmentRecord.difficult?.score },
            ].map((t) => (
              <button
                key={t.id}
                onClick={() => handleSelectTier(t.id)}
                style={{
                  padding: "6px 14px",
                  border: `1px solid ${selectedTier === t.id ? coral : border}`,
                  background: selectedTier === t.id ? (t.passed ? "#D1FAE5" : "#FFF5F3") : "#fff",
                  color: selectedTier === t.id ? (t.passed ? emerald : coral) : slate,
                  fontSize: 11,
                  fontWeight: 700,
                  borderRadius: 4,
                  cursor: "pointer",
                  fontFamily: "'Space Grotesk', sans-serif",
                  display: "flex",
                  alignItems: "center",
                  gap: 6,
                }}
              >
                <span>{t.label}</span>
                {t.passed ? (
                  <span style={{ color: emerald, fontSize: 10 }}>✓ {t.score}%</span>
                ) : t.score !== undefined ? (
                  <span style={{ color: coral, fontSize: 10 }}>✗ {t.score}%</span>
                ) : null}
              </button>
            ))}
          </div>

          <div style={{ marginLeft: "auto", fontSize: 11, color: muted }}>
            Requirement: <b>≥70%</b> on all 3 tiers to mark course completed
          </div>
        </div>

        {/* Quiz Body */}
        <div style={{ flex: 1, overflowY: "auto", padding: "24px 28px" }}>
          {/* Progress Tracker */}
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: slate }}>
              Question {currentIdx + 1} of {totalQuestions}
            </div>
            <div style={{ display: "flex", gap: 6 }}>
              {questions.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setCurrentIdx(i)}
                  style={{
                    width: 28,
                    height: 28,
                    borderRadius: 4,
                    border: `1px solid ${i === currentIdx ? coral : selectedOptions[i] !== undefined ? emerald : border}`,
                    background: i === currentIdx ? coral : selectedOptions[i] !== undefined ? "#D1FAE5" : "#fff",
                    color: i === currentIdx ? "#fff" : selectedOptions[i] !== undefined ? emerald : muted,
                    fontSize: 11,
                    fontWeight: 700,
                    cursor: "pointer",
                  }}
                >
                  {i + 1}
                </button>
              ))}
            </div>
          </div>

          {/* Question Card */}
          <div
            style={{
              background: "#fff",
              border: `1px solid ${border}`,
              padding: "20px 24px",
              borderRadius: 6,
              marginBottom: 20,
            }}
          >
            <div style={{ fontSize: 10, color: muted, fontFamily: "'Space Grotesk', sans-serif", letterSpacing: "0.08em", marginBottom: 8 }}>
              {selectedTier.toUpperCase()} ASSESSMENT · QUESTION {currentIdx + 1}
            </div>
            <div style={{ fontSize: 15, fontWeight: 600, color: slate, lineHeight: 1.6 }}>
              {currentQ.question}
            </div>

            {currentQ.options.length === 0 && (
              <div style={{ marginTop: 18, display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" }}>
                <button
                  onClick={() => {
                    setSelectedDomainFilter("all");
                    setRagSession(null);
                  }}
                  style={{
                    padding: "8px 18px",
                    background: coral,
                    color: "#fff",
                    border: "none",
                    borderRadius: 4,
                    fontSize: 12,
                    fontWeight: 700,
                    cursor: "pointer",
                  }}
                >
                  Switch to Official iGOT Courses →
                </button>
                <button
                  onClick={() => handleGenerateRagAssessment()}
                  disabled={isGeneratingRag}
                  style={{
                    padding: "8px 16px",
                    background: "#fff",
                    border: `1px solid ${border}`,
                    color: slate,
                    borderRadius: 4,
                    fontSize: 12,
                    fontWeight: 600,
                    cursor: isGeneratingRag ? "not-allowed" : "pointer",
                  }}
                >
                  {isGeneratingRag ? "Connecting to AI Engine..." : "Retry Document Generation"}
                </button>
              </div>
            )}
          </div>

          {/* Options */}
          <div style={{ display: "flex", flexDirection: "column", gap: 10, marginBottom: 24 }}>
            {currentQ.options.map((opt, optIdx) => {
              const isSelected = selectedOptions[currentIdx] === optIdx;
              const isCorrect = optIdx === currentQ.correctIndex;
              const showResult = isSubmitted;

              let optionBg = "#fff";
              let optionBorder = border;

              if (showResult) {
                if (isCorrect) {
                  optionBg = "#D1FAE5";
                  optionBorder = emerald;
                } else if (isSelected && !isCorrect) {
                  optionBg = "#FFF5F3";
                  optionBorder = coral;
                }
              } else if (isSelected) {
                optionBg = "#FFF5F3";
                optionBorder = coral;
              }

              return (
                <div
                  key={optIdx}
                  onClick={() => handleOptionSelect(optIdx)}
                  style={{
                    padding: "14px 18px",
                    border: `1px solid ${optionBorder}`,
                    background: optionBg,
                    borderRadius: 6,
                    cursor: isSubmitted ? "default" : "pointer",
                    display: "flex",
                    alignItems: "flex-start",
                    gap: 12,
                  }}
                >
                  <div
                    style={{
                      width: 24,
                      height: 24,
                      borderRadius: "50%",
                      border: `1px solid ${optionBorder}`,
                      background: isSelected ? coral : "#fff",
                      color: isSelected ? "#fff" : muted,
                      fontSize: 11,
                      fontWeight: 700,
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      flexShrink: 0,
                    }}
                  >
                    {String.fromCharCode(65 + optIdx)}
                  </div>
                  <div style={{ fontSize: 13, color: slate, lineHeight: 1.5, paddingTop: 2 }}>
                    {opt}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Explanation if submitted */}
          {isSubmitted && (
            <div
              style={{
                background: selectedOptions[currentIdx] === currentQ.correctIndex ? "#F0FDF4" : "#FFF5F3",
                border: `1px solid ${selectedOptions[currentIdx] === currentQ.correctIndex ? emerald : coral}`,
                padding: "16px 20px",
                borderRadius: 6,
                marginBottom: 20,
              }}
            >
              <div style={{ fontSize: 11, fontWeight: 700, color: selectedOptions[currentIdx] === currentQ.correctIndex ? emerald : coral, marginBottom: 4 }}>
                {selectedOptions[currentIdx] === currentQ.correctIndex ? "✓ CORRECT" : "✗ INCORRECT"} — STATUTORY EXPLANATION:
              </div>
              <div style={{ fontSize: 12, color: slate, lineHeight: 1.55 }}>
                {currentQ.explanation}
              </div>
            </div>
          )}

          {/* Action Bar */}
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <div style={{ display: "flex", gap: 10 }}>
              <button
                disabled={currentIdx === 0}
                onClick={() => setCurrentIdx((c) => Math.max(0, c - 1))}
                style={{
                  padding: "8px 16px",
                  background: "#fff",
                  border: `1px solid ${border}`,
                  color: currentIdx === 0 ? muted : slate,
                  fontSize: 12,
                  fontWeight: 600,
                  borderRadius: 4,
                  cursor: currentIdx === 0 ? "not-allowed" : "pointer",
                }}
              >
                ← Previous
              </button>

              {currentIdx < totalQuestions - 1 && (
                <button
                  onClick={() => setCurrentIdx((c) => Math.min(totalQuestions - 1, c + 1))}
                  style={{
                    padding: "8px 16px",
                    background: slate,
                    border: `1px solid ${slate}`,
                    color: "#fff",
                    fontSize: 12,
                    fontWeight: 700,
                    borderRadius: 4,
                    cursor: "pointer",
                  }}
                >
                  Next Question →
                </button>
              )}
            </div>

            {!isSubmitted ? (
              <button
                onClick={handleGradeAssessment}
                disabled={Object.keys(selectedOptions).length < totalQuestions}
                style={{
                  padding: "10px 24px",
                  background: Object.keys(selectedOptions).length === totalQuestions ? emerald : "#CBD5E1",
                  border: "none",
                  color: "#fff",
                  fontSize: 12,
                  fontWeight: 700,
                  borderRadius: 4,
                  cursor: Object.keys(selectedOptions).length === totalQuestions ? "pointer" : "not-allowed",
                  boxShadow: Object.keys(selectedOptions).length === totalQuestions ? "0 2px 8px rgba(5, 150, 105, 0.25)" : "none",
                }}
              >
                Submit & Grade {selectedTier.toUpperCase()} Assessment ✓
              </button>
            ) : (
              <div style={{ display: "flex", gap: 10, alignItems: "center" }}>
                <button
                  onClick={() => {
                    setSelectedOptions({});
                    setIsSubmitted(false);
                    setCurrentIdx(0);
                    setLatestScorePercent(null);
                  }}
                  style={{
                    padding: "8px 16px",
                    background: "#fff",
                    border: `1px solid ${coral}`,
                    color: coral,
                    fontSize: 12,
                    fontWeight: 700,
                    borderRadius: 4,
                    cursor: "pointer",
                  }}
                >
                  Retry Tier Assessment
                </button>

                {selectedTier === "easy" && (
                  <button
                    onClick={() => handleSelectTier("medium")}
                    style={{
                      padding: "8px 18px",
                      background: coral,
                      border: "none",
                      color: "#fff",
                      fontSize: 12,
                      fontWeight: 700,
                      borderRadius: 4,
                      cursor: "pointer",
                    }}
                  >
                    Proceed to Tier 2 (Medium) →
                  </button>
                )}

                {selectedTier === "medium" && (
                  <button
                    onClick={() => handleSelectTier("difficult")}
                    style={{
                      padding: "8px 18px",
                      background: coral,
                      border: "none",
                      color: "#fff",
                      fontSize: 12,
                      fontWeight: 700,
                      borderRadius: 4,
                      cursor: "pointer",
                    }}
                  >
                    Proceed to Tier 3 (Difficult) →
                  </button>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Course Study Modal */}
      {studyModalCourseId && (
        <CourseContentModal
          courseId={studyModalCourseId}
          isOpen={Boolean(studyModalCourseId)}
          onClose={() => setStudyModalCourseId(null)}
          onStartAssessment={(cId, tier) => {
            setStudyModalCourseId(null);
            setSelectedCourseId(cId);
            handleSelectTier(tier);
          }}
        />
      )}
    </div>
  );
}
