"""
Data models for assessments, questions, submissions, and mastery records.
Strictly implements the MCQ Contract defined in PERSON_2.md.
"""

from typing import List, Optional, Dict
from pydantic import BaseModel, Field


class MCQQuestion(BaseModel):
    """
    Contract-compliant Multiple Choice Question.
    Directly reflects PERSON_2.md Section MCQ Contract.
    """
    id: Optional[str] = None
    question: str = Field(..., description="Clear question text testing competency")
    option_a: str = Field(..., description="First option")
    option_b: str = Field(..., description="Second option")
    option_c: str = Field(..., description="Third option")
    option_d: str = Field(..., description="Fourth option")
    correct_option: str = Field(..., description="'A', 'B', 'C', or 'D'")
    explanation: str = Field(..., description="Grounded explanation citing factual evidence")
    source_document: str = Field(..., description="Document identifier or filename")
    source_page: int = Field(..., description="Page number where evidence appears")


class MCQValidationResult(BaseModel):
    """Result of automated contract validation on a generated question."""
    is_valid: bool
    errors: List[str] = Field(default_factory=list)
    question: Optional[MCQQuestion] = None


class AssessmentGenerationRequest(BaseModel):
    """Request payload to initiate RAG assessment generation."""
    employee_id: str
    department_id: str = "default"
    competency_id: str
    competency_name: str
    difficulty: int = Field(default=1, ge=1, le=5)
    question_count: int = Field(default=15, ge=1, le=15)
    document_id: Optional[str] = Field(default=None, description="Restrict retrieval to one approved indexed document")


class AssessmentSession(BaseModel):
    """Assessment presented to the learner (answers omitted for client-side security)."""
    assessment_id: str
    employee_id: str
    competency_id: str
    competency_name: str
    difficulty: int
    questions: List[Dict] = Field(..., description="Questions with correct_option and explanation masked")


class AnswerItem(BaseModel):
    """Single question response submitted by learner."""
    question_id: str
    selected_option: str = Field(..., description="Learner's answer: 'A', 'B', 'C', or 'D'")


class QuizSubmission(BaseModel):
    """Full quiz submission for deterministic scoring."""
    assessment_id: str
    employee_id: str
    competency_id: str
    answers: List[AnswerItem]


class QuestionReviewItem(BaseModel):
    """Itemized review detail for each question after scoring."""
    question_id: str
    question_text: str
    selected_option: str
    correct_option: str
    is_correct: bool
    explanation: str
    source_document: str
    source_page: int


class MasteryTier(BaseModel):
    """Categorized level of demonstrated mastery."""
    tier_name: str
    score_percentage: float
    description: str


class AssessmentResult(BaseModel):
    """
    Authoritative, deterministic assessment scoring outcome.
    Never generated by AI.
    """
    assessment_id: str
    employee_id: str
    competency_id: str
    total_questions: int
    correct_answers: int
    score_percentage: float
    mastery_tier: str
    mastery_description: str
    competency_level_recommended: int
    review_items: List[QuestionReviewItem]
